name: Update

permissions: {}

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      # setup
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: jdx/mise-action@e3d7b8d67a7958d1207f6ed871e83b1ea780e7b0 # v3.3.1

      # install dependencies
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
      - run: bun install --frozen-lockfile

      # run updates
      - run: bun run fetch:versions
      - run: bun run fetch:changelog
      - run: bun run build:feed

      # commit & push changes
      - name: set git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: commit and push changes
        run: |
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "chore: Update"
            git push origin main
          else
            echo "No changes to commit"
          fi
